kind: pipeline
type: docker
name: build node 14

steps:
  - name: install
    pull: if-not-exists
    image: node:14
    commands:
      - npm ci

  - name: prepare
    image: node:14
    commands:
      - npm run prepare

trigger:
  branch:
    - main

---
kind: pipeline
type: docker
name: build node 18

steps:
  - name: install
    pull: if-not-exists
    image: node:18
    commands:
      - npm ci

  - name: prepare
    image: node:18
    commands:
      - npm run prepare

trigger:
  branch:
    - main

---
kind: pipeline
type: docker
name: build node 16

steps:
  - name: install
    pull: if-not-exists
    image: node:16
    commands:
      - npm ci

  - name: prepare
    image: node:16
    commands:
      - npm run prepare

trigger:
  branch:
    - main
